---
- name: Update /etc/issue
  ansible.builtin.copy:
    src: issue
    dest: /etc/issue

- ansible.builtin.import_tasks:
    file: ssh.yml
    
- ansible.builtin.import_tasks:
    file: repos.yml

- ansible.builtin.import_tasks:
    file: packages.yml

- ansible.builtin.import_tasks:
    file: modules.yml